sudo: required
dist: trusty
language: node_js

script:
 - npm run build
 - npm run surge-github-autorelease -r $TRAVIS_REPO_SLUG -s $STORYBOOK_DIST -p $TRAVIS_PULL_REQUEST -t $GITHUB_API_TOKEN

notifications:
  email:
    recipients:
      - fed-infra@wix.com
